version: "3"

services:
  caddy:
    build:
      context: ./src/caddy
    ports:
      - "8080:8080"
    volumes:
      - ./caddy:/root/.caddy
      - ./src/caddy/Caddyfile:/etc/Caddyfile
    entrypoint: "caddy --conf /etc/Caddyfile"
    networks:
      - test
    restart: unless-stopped
  react:
    build:
      context: ./src/react
    networks:
      - test
    restart: unless-stopped

networks:
  test:
